apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/openshift
    repoURL: 'https://github.com/ogaye-ibm/ecm-cicd-argocd'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
